/**
 * Supabase client configuration
 * Generated by Roo
 */
import { createClient } from '@supabase/supabase-js';

// Get environment variables
const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL as string || '';
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY as string || '';

// Create Supabase client
export const supabase = createClient(supabaseUrl, supabaseAnonKey);

export const setupTransactions = async () => {
  try {
    await supabase.rpc('create_begin_transaction_procedure', {}, {
      count: 'exact',
    });
    
    await supabase.rpc('create_commit_transaction_procedure', {}, {
      count: 'exact',
    });
    
    await supabase.rpc('create_rollback_transaction_procedure', {}, {
      count: 'exact',
    });
    
    console.debug('Transaction procedures set up successfully');
  } catch (error) {
    console.error('Error setting up transaction procedures:', error);
  }
};