'use client';

import { useEffect } from 'react';
import { setupTransactions } from '@/lib/supabase';
/**
 * Home Page with React Flow Diagram
 * Generated by Roo
 */
import dynamic from 'next/dynamic';

const SystemDiagram = dynamic(() => import('@/components/SystemDiagram'), {
  ssr: false,
});

export default function Home() {
  useEffect(() => {
    setupTransactions();

    // Add some console.debug statements to help trace React state
    console.debug('Application initialized');
  }, []);

  return (
    <div className='container mx-auto p-4'>
      <h1 className='text-2xl font-bold mb-4'>
        Next.js + Supabase + React Flow
      </h1>
      <div className='border rounded-lg overflow-hidden'>
        {/* <FlowDiagram /> */}
        <SystemDiagram />
      </div>
    </div>
  );
}
